# Dockerfile para desenvolvimento do Adminer Frontend
FROM node:24-alpine

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de configuração do npm para o contêiner
COPY svelte-app /app/svelte-app

# Instala as dependências do projeto
WORKDIR /app/svelte-app

# Instala as dependências do projeto
RUN npm install

# Expõe a porta que a aplicação irá rodar
EXPOSE 5173

# Define o comando padrão para iniciar a aplicação em modo de desenvolvimento
CMD ["npm", "run", "dev"]